[book]
title = "Warp Parse Documentation"
authors = ["Warp Parse Team"]
language = "en"
src = "."

[build]
build-dir = "../book/en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/wp-labs/warp-parse"
preferred-dark-theme = "light"
additional-css = ["../theme/site.css", "../theme/lang-switch.css", "../theme/version-badge.css"]
additional-js = ["../theme/lang-switch.js", "../theme/version-badge.js", "../theme/site.js", "mermaid.min.js", "mermaid-init.js"]
