[book]
title = "Warp Parse 文档"
authors = ["Warp Parse Team"]
language = "zh-CN"
src = "."

[build]
build-dir = "../book/zh"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/wp-labs/warp-parse"
preferred-dark-theme = "navy"
additional-css = ["theme/site.v20260507-1.css"]
additional-js = ["theme/site.v20260507-1.js", "mermaid.min.js", "mermaid-init.js"]
