[book]
title = "Warp Parse Documentation [BETA]"
authors = ["Warp Parse Team"]
language = "en"
src = "."

[build]
build-dir = "../book/en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/wp-labs/warp-parse"
preferred-dark-theme = "navy"
additional-css = ["theme/site.css"]
additional-js = ["theme/site.js", "mermaid.min.js", "mermaid-init.js"]
